### ISSUE TITLE
QiniuUtils工具类中的Key怎么配呢

### ISSUE THREAD

**Issue by DoublePeach** [bfury/health_management_system#92]
QiniuUtils工具类中的Key怎么配呢？

**Comment by bfury** [comment]
Access Key 对应 AccessKey ID（AK)
Secret Key 对应 AccessKey Secret (SK) 
Bucket 对应 Bucket 名称（名称是创建时填写的存储空间名称）
在七牛云-个人中心-密钥管理、和七牛云-对象存储-空间管理
